### PR TITLE
feat: supported dCKB

### PR DESCRIPTION
**Pull request by homura**

### CODE REVIEW

**Comment by VISQonSpotify** [comment]
Yes, please! I have dCKB stuck and would be very appreciative if this gets done.

**Comment by homura** [comment]
hi, @VISQonSpotify do you have an account with a small dCKB balance? you can try this [link](https://pw-up-git-dckb-cryptape.vercel.app/)

**Comment by VISQonSpotify** [comment]
> hi, @VISQonSpotify do you have an account with a small dCKB balance? you can try this [link](https://pw-up-git-dckb-cryptape.vercel.app/)

Hi, thanks. I have more than 20. It's xx,xxx amount.

**Comment by VISQonSpotify** [comment]
> hi, @VISQonSpotify do you have an account with a small dCKB balance? you can try this [link](https://pw-up-git-dckb-cryptape.vercel.app/)

Ah, I read this incorrectly. So I need to have some dCKB in the wallet to be able to use this tool? Because it's greyed out when I choose lina.

**Pull request merged**
